### ISSUE TITLE
Missing CLS Unit?

### ISSUE THREAD

**Issue by CMDRCOREX** [discoADFU/Project_Uncut_Issues#108]
I've been using Uncut for some time now and even in mission making. However whenever I try to bring up a scenario with the mod it says 'ADFU_AMCU_CLS'. To me it seems that there is a unit class missing and now i am unable to continue my mission. Is there any way that this can be fixed or that i can get around it somehow?

**Comment by TheLJFox** [comment]
This error of your is due to the most recent update. I warning was given out prior to the update stating that classnames for all units had changed and future missions may not be backward compatible.  'ADFU_AMCU_CLS' is a classname of a unit in the previous version and has since been deprecated. 

To get around this, on a blank map of the same name that your mission is on, go to 'Scenario>Merge' then choose your old mission to merge. Doing this will copy over everything from your mission to a blank canvas minus the missing units and errors relating to them. All you'll have to do from that is just place down the CLS unit and add any scripts that you may have had in the mission directory and everything should work again. 

Hope that helps,
LJ
